<div class="jumbotron">
<h2>CS&amp;SS/STAT 564: Bayesian Statistics</h2>
<h4>University of Washington, <small>Spring 2017</small></h4>
<br/>
<h4>Instructor: <a href="http://jrnold.io/">Jeffrey Arnold</a></h4>
<h4>TA: <a href="https://www.stat.washington.edu/personnel/people.php?id=748">Sheridan Grant</a></h4>
</div>

# Overview

# Prerequisites

Students should have have a basic understanding of probability, classical statistics and hypothesis testing, linear regression, and maximum likelihood estimation (MLE).
Students should be familiar or proficient with the R programming language.

# Logistics

#### Teaching Team

<table class = "table table-striped">
<tr>
<td>
<strong>Primary</strong>
</td>
<td><a href="http://jrnold.me"><strong>Jeffrey Arnold</strong></a></td>
<td><a href="mailto:jrnold@uw.edu">jrnold@uw.edu</a></td>
</tr>
<tr>
<td>
<strong></strong>
</td>
<td>
<a href="https://www.stat.washington.edu/personnel/people.php?id=748">Sheridan Grant</a>
</td>
<td>
<a href="mailto:slgstats@uw.edu">slgstats@uw.edu</a>
</td>
</tr>
</table>

#### Meetings

<table class = "table table-striped table-hover">
<tr>
<td>Class </td>
<td>T,Th </td>
<td> 2:30&ndash;3:50 pm </td>
<td><a href="https://www.washington.edu/maps/?cdh">CDH 717</td>
</tr>
<tr>
<td>Lab </td>
<td>Th</td>
<td>1:30&ndash;2:20 pm </td>
<td><a href="https://www.washington.edu/maps/?cdh">CDH 717</a></td>
</tr>
</table>

#### Office Hours

<!-- commit -->

<table class = "table table-striped">
<tr>
<td>Jeff</td>
<td>M</td>
<td>11:00 am&ndash;1:00 pm</td>
<td><a href="https://www.washington.edu/maps/?smi">SMI 221B</a></td>
</tr>
<tr>
<td>Sheridan</td>
<td>M 3:30-4:20</td>
<td>F 2:30-3:20</td>
<td><a href="https://www.washington.edu/maps/?cmu">CMU B023</a></td>
</tr>

</table>

Instructions for Jeff's office hours:

1. Sign up for a 30-minute slot using the Google Calendar appointments link emailed to the class.

2. Email me 24 hours prior to your appointment with what you would like to discuss.

These instructions will ensure that our time is efficiently spent and I can be of the most help to you.

#### Communication

In this course we will be using [Slack](https://slack.com/) for online class discussion. You will not be required to post, but the system is designed to get you help quickly and efficiently from classmates, and the instructors.
Rather than emailing questions to the instructors, post your questions to the [course Slack](https://uwcsss564.slack.com/).
You should have received an invitation to join this team, if not contact us to receive an invite.

# Evaluation

Evaluation will consist of problem sets and participation.

- Problem Sets: 75%
    - Solutions: 25%
    - Peer Evaluation: 25%
    - Self-Correction: 25%
- Participation: 25%

#### Problem Sets

These will be assigned on Tuesday and due the following Tuesday prior to class. They will consist of both applied and theoretical questions. Evaluation of the problem set will consist of three components. 

1. **Solutions:** The initial answers to problem sets will be graded as "excellent", "satisfactory", or "unsatisfactory."

2. **Peer Evaluations:** Each student will be randomly assigned two other students' assignments to grade. The peer evaluations themselves will receive grades of "satisfactory" or "unsatisfactory".

3. **Corrections:** After receiving the solution key and comments on their initial submission, students must correct their problem sets. These corrections will take the form of an updated assignment which (1) indicates where mistakes were made, (2) indicates the correct answer, (3) and demonstrates an understanding of how these mistakes were made and how those mistakes differ from the correct answer. 

#### Participation 

Students must actively participate in all parts of the course. 
This will consist of pre-lecture assignments in which students will be asked to contribute questions or content, as well as participation on Slack.
The details of how this will be evaluated will evolve over the course.


# Texts

- McElreath. 2015. [Statistical Rethking](https://www.crcpress.com/Statistical-Rethinking-A-Bayesian-Course-with-Examples-in-R-and-Stan/McElreath/p/book/9781482253443). The [CRC page](https://www.crcpress.com/Statistical-Rethinking-A-Bayesian-Course-with-Examples-in-R-and-Stan/McElreath/p/book/9781482253443) has an eBook, though [Amazon](https://www.amazon.com/Statistical-Rethinking-Bayesian-Examples-Chapman/dp/1482253445) does not.
- (Optional) Gelman, Andrew, John B. Carlin, Hal S. Stern, David B. Dunson, Aki Vehtrai, and Donald B. Rubin. 2013. [Bayesian Data Analysis](https://www.amazon.com/Bayesian-Analysis-Chapman-Statistical-Science/dp/1439840954/ref=dp_ob_title_bk). 3rd ed. The 3rd edition is significantly changed from the 2nd edition. This provides a good reference for concepts and models beyond what is covered in *Statistical Rethinking*

*BDA3* is is optional, but will go into more depth than *Stat Rethinking* and will be used if we get through the material in *Stat Rethinking* quicker than expected.

Additional readings are on the [schedule](schedule.html).

# Software

For computation, this course will rely upon

- [R](https://cran.r-project.org/): a language for statistical computing
- [Stan](http://mc-stan.org/): a probabilistic programming language for writing and estimating Bayesian models

Both **R** and **Stan** are free and open-source. 

I expect that students will already be familiar with **R**, so class time will not be spent introducing it in order to familiarize students with **Stan**.

Though not necessary, you are encouraged to use [RStudio](https://www.rstudio.com/products/rstudio/#Desktop) Desktop integrated development environment (IDE) for R.
