---
title: "CS&SS/STAT 564 Schedule"
bibliography: _submodules/bayesian_notes/bayes.bib
---

```{r include=FALSE}
library("yaml")
library("htmltools")
library("purrr")
library("stringr")
library("lubridate")

localdata <- yaml.load_file("data.yml")
render_week <- function(x) {
  w <- x[["week"]]
  classes <-  map(x[["meetings"]], render_class)
  hdr <- tagList(tags$hr(), tags$h2(str_c("Week ", w)))
  div(id = str_c("week-", w), hdr, classes)
}

render_reading <- function(x) {
  tags$li(HTML(commonmark::markdown_html(x)))
}

render_notes <- function(x) {
  tags$p(HTML(commonmark::markdown_html(x[["notes"]])))
}

render_readings_before <- function(x) {
  readings <- x[["reading_before"]]
  if (length(readings) > 0) {
    tags$p(
      str_c("Readings before class:"),
      tags$ul(map(readings, render_reading))
    )    
  } else ""
}

render_readings_after <- function(x) {
  readings <- x[["reading_after"]]
  if (length(readings) > 0) {
    tags$p(
      str_c("Optional readings after class:"),
      tags$ul(map(readings, render_reading))
    )
  } else ""
}

render_in_class_item <- function(x) {
  tags$li(HTML(commonmark::markdown_html(x)))
}

render_in_class_items <- function(x) {
  readings <- x[["in_class"]]
  if (length(readings) > 0) {
    tags$p(
      str_c("In class:"),
      tags$ul(map(readings, render_in_class_item))
    )
  } else ""
}


render_topics <- function(x) {
  topics <- x[["topics"]]
  if (length(topics)) {
    tags$p(tags$strong("Topics:"), HTML(commonmark::markdown_html(topics)))
  }
}

render_class <- function(x) {
  start <- ymd_hm(x[["start"]])
  end <- ymd_hm(x[["end"]])
  .header <- h3(str_c(str_to_title(x[["type"]]), ": "),
                tags$time(format(start, "%A, %B %d, %Y"),
                          tags$small(format(start, "%H:%M"),
                                     HTML("&ndash;"),
                                     format(end, "%H:%M")),
                          datetime = format(start, "%Y-%m-%d %H:%M")))
  div(
    id = str_c(x[["type"]], "-", format(start, "%Y-%m-%d")),
    .header,
    render_topics(x),
    render_notes(x),    
    render_readings_before(x),
    render_readings_after(x),
    render_in_class_items(x)
  )
}

render_assignment <- function(x) {
  tags$tr(
    tags$td(tags$a(href = x[["url"]], x[["name"]])),
    tags$td(HTML(format(ymd_hm(x[["due-date"]]), "%a, %b %d, %Y %H:%M")))
  )
}

render_assignments <- function(x) {
   tags$div(tags$p(tags$table(
     class = "table table-striped",
     tags$tr(
       tags$th("Assignment"),
       tags$th("Due date")
     ),
     map(x, render_assignment)
   )))
}

```

# Assignments

Follow the instructions for assignments [here](assignments.html)


```{r echo=FALSE}
render_assignments(localdata[["assignments"]])
```



# Readings

```{r echo = FALSE}
tagList(map(localdata[["classes"]], render_week))
```
